-- 감사 컬럼 추가 마이그레이션
-- created_at, updated_at, created_id, updated_id
-- 생성일: 2026-03-06

SET NAMES utf8mb4;

ALTER TABLE `alimtalk_logs`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `app_banners`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `app_faqs`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `app_feedbacks`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `app_menus`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `app_terms`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `app_versions`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `attendance_qr_codes`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `audit_logs`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `badges`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `chat_messages`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `chat_room_members`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `chat_rooms`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `child_badges`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `child_profiles`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `class_attendances`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `class_products`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `class_registrations`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `class_reviews`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `class_schedules`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `classes`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_event_registrations`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_events`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_invites`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_members`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_post_attachments`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_post_comments`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_post_likes`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `club_posts`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `clubs`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `coach_profiles`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `coupons`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `credit_transactions`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `daily_metrics`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `enrollments`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `hockey_matches`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `identity_verifications`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `identity_webhook_logs`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `match_events`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `match_periods`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `member_credits`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `member_levels`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `notification_templates`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `notifications`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `parent_children`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `parent_profiles`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `payment_webhooks`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `payments`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `pickup_match_applicants`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `pickup_matches`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `point_transactions`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `refund_logs`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `rinks`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `settlement_transactions`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `settlements`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_categories`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_order_items`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_orders`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_product_images`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_product_options`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_products`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_reviews`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_shipping_companies`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_shippings`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `shop_wishlists`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `skill_dimensions`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `skill_evaluations`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `system_notices`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `team_rosters`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `teams`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `tournaments`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `user_coupons`
  ADD COLUMN IF NOT EXISTS `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `user_devices`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `user_notification_preferences`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;

ALTER TABLE `venues`
  ADD COLUMN IF NOT EXISTS `created_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `updated_id` VARCHAR(191) NULL;
